name: 3proxy

services:
  3proxy:
    image: 3proxy/3proxy
    ports:
      - "0.0.0.0:${EXTERNAL_PORT:-11081}:1080"
    volumes:
      - ./config/3proxy.cfg:/etc/3proxy/3proxy.cfg
      - ./config/users.lst:/etc/3proxy/users.lst
    restart: unless-stopped
