version: '3.8'

networks:
  traefik:
    external: true

services:
  typesense:
    image: typesense/typesense:0.25.2
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    restart: unless-stopped
    ports:
      - 8108
    volumes:
      - ./typesense-data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.ts1-web.rule=Host(`${DOMAIN_NAME}`)
      - traefik.http.services.ts1-web.loadbalancer.server.port=8108
      - traefik.http.routers.ts1-web.entrypoints=websecure
      - traefik.http.routers.ts1-web.tls.certresolver=my
      - traefik.docker.network=traefik

      - com.centurylinklabs.watchtower.enable=true
    networks:
      - traefik
